import {SearchDataArrayType} from './types';

export const mockSearchData: SearchDataArrayType = [
  {id: 1, name: 'Strawberry Symphony'},
  {id: 2, name: 'Banana Boogie'},
  {id: 3, name: 'Pineapple Paradise'},
  {id: 4, name: 'Mango Mambo'},
  {id: 5, name: 'Watermelon Whirl'},
  {id: 6, name: 'Citrus Samba'},
  {id: 7, name: 'Grape Groove'},
  {id: 8, name: 'Peachy Paso Doble'},
  {id: 9, name: 'Kiwi Quickstep'},
  {id: 10, name: 'Apple Jive'},
  {id: 11, name: 'Pear Promenade'},
  {id: 12, name: 'Melon Merengue'},
  {id: 13, name: 'Lemon Lindy Hop'},
  {id: 14, name: 'Blueberry Ballet'},
  {id: 15, name: 'Cherry Cha-Cha'},
  {id: 16, name: 'Strawberry Samba'},
  {id: 17, name: 'Banana Beat'},
  {id: 18, name: 'Pineapple Polka'},
  {id: 19, name: 'Mango Macarena'},
  {id: 20, name: 'Watermelon Waltz'},
  {id: 21, name: 'Orange Overture'},
  {id: 22, name: 'Grapevine Gala'},
  {id: 23, name: 'Peach Prom'},
  {id: 24, name: 'Kiwi Kizomba'},
  {id: 25, name: 'Apple Allegro'},
  {id: 26, name: 'Pear Paso'},
  {id: 27, name: 'Melon Mambo'},
  {id: 28, name: 'Lemon Leap'},
  {id: 29, name: 'Blueberry Boogie'},
  {id: 30, name: 'Cherry Charleston'},
];
